#!/usr/bin/env bash
# seed_@@SLUG@@.sh — generated by khwab @@VERSION@@.
#   bash seed_@@SLUG@@.sh          stage only, nothing upstream
#   bash seed_@@SLUG@@.sh --push   gh repo create -> seal -> push -> VERIFY -> Pages
#   bash seed_@@SLUG@@.sh --mint   misty ots stamp -> rehearsal -> gate -> publish -> record back
#
# The deployment is KITAB-SHAPED: index.html at root, js/, readers/, assets/theme/ come from the
# template verbatim; config/, content/ and assets/ are ours. A @@KIND@@ book reads in the same
# reader as every other book in the estate.
set -uo pipefail
VERSION="@@VERSION@@"
SLUG="${@@ENV@@_SLUG:-@@REPO@@}"
LOCAL="${@@ENV@@_LOCAL:-@@SLUG@@-repo}"
TEMPLATE="${@@ENV@@_TEMPLATE:-zistgah/kitab}"
TEMPLATE_DIR="${@@ENV@@_TEMPLATE_DIR:-kitab-src}"
BRANCH="${@@ENV@@_BRANCH:-main}"; VISIBILITY="${@@ENV@@_VISIBILITY:-public}"
ESTATE="${@@ENV@@_ESTATE:-/shared/estate/github}"; FORGE="${ZOPS_FORGE:-https://github.com}"
TITLE="@@TITLE@@"; NCHAP=@@NCHAP@@; KIND="@@KIND@@"; MEDIA="@@MEDIA@@"
MINT_WORD="MINT @@SLUG@@"
ZENODO_TOKEN_PATH="${ZENODO_TOKEN_PATH:-$HOME/Documents/zenodo_token_20260612}"
ROOT="$PWD"; HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"; LOGD="$ROOT/logs"; mkdir -p "$LOGD"
LOG="$LOGD/@@SLUG@@.$STAMP.log"
DO_PUSH=0; DO_MINT=0; OVERRIDE_REHEARSAL=0
say(){ printf '[@@SLUG@@] %s\n' "$*" | tee -a "$LOG"; }
warn(){ printf '[@@SLUG@@] WARN  %s\n' "$*" | tee -a "$LOG" >&2; }
die(){ printf '[@@SLUG@@] FATAL %s\n' "$*" | tee -a "$LOG" >&2; exit 1; }
have(){ command -v "$1" >/dev/null 2>&1; }
inside(){ case "$(cd "$1" 2>/dev/null && pwd)/" in "$ROOT"/*) return 0;; *) return 1;; esac; }
while [ $# -gt 0 ]; do case "$1" in
  --push) DO_PUSH=1;; --mint) DO_MINT=1;; --override-rehearsal) OVERRIDE_REHEARSAL=1;;
  --slug) shift; SLUG="$1";; -h|--help) sed -n '2,10p' "$0"; exit 0;; *) die "unknown flag: $1";;
esac; shift; done

# Clause A, hardened: an INCOMPLETE directory is not a source. Test the whole shipped set.
resolve_src(){ local c
  for c in "$HERE" "$ROOT" "$HERE/@@SLUG@@" "$ROOT/@@SLUG@@"; do
    [ -f "$c/payload/book.config.json" ] && [ -d "$c/payload/content" ] \
      && [ -d "$c/payload/assets" ] && [ -f "$c/metadata/misty.json" ] \
      && { SRC="$(cd "$c" && pwd)"; return 0; }
  done
  local tb; for tb in "$ROOT"/@@SLUG@@*.tar "$HERE"/@@SLUG@@*.tar; do
    [ -f "$tb" ] || continue; say "extracting $(basename "$tb")"
    tar -xf "$tb" -C "$ROOT" && { resolve_src && return 0; }
  done
  die "payload incomplete or absent. Put @@SLUG@@.tar beside this script."; }

resolve_template(){ local d="$ROOT/$TEMPLATE_DIR"
  if [ -d "$d/.git" ]; then say "template reuse: $TEMPLATE_DIR"
    ( cd "$d" && git fetch -q origin && git reset --hard -q FETCH_HEAD ) 2>>"$LOG" || warn "template refresh failed"
  elif [ -d "$ESTATE/${TEMPLATE%%/*}/${TEMPLATE##*/}/.git" ]; then
    say "template from canonical estate mirror (C38)"
    git clone -q "$ESTATE/${TEMPLATE%%/*}/${TEMPLATE##*/}" "$d" || die "clone from estate failed"
  else say "cloning template $TEMPLATE"
    if have gh; then gh repo clone "$TEMPLATE" "$d" -- -q || die "gh repo clone failed"
    else git clone -q "$FORGE/$TEMPLATE.git" "$d" || die "git clone failed"; fi; fi
  [ -f "$d/index.html" ] || die "$TEMPLATE_DIR/index.html absent — not a kitab tree"
  TPL="$d"; say "template HEAD: $(cd "$TPL" && git rev-parse --short HEAD 2>/dev/null || echo '?')"; }

create_remote_if_needed(){ have gh || { warn "gh absent"; return 1; }
  gh repo view "$SLUG" >/dev/null 2>&1 && { say "remote exists: $SLUG"; return 0; }
  say "remote $SLUG does NOT exist upstream — creating it now, before any seal"
  local out rc; out="$(gh repo create "$SLUG" "--$VISIBILITY" --description "$TITLE" 2>&1)"; rc=$?
  printf '%s\n' "$out" >>"$LOG"
  if [ $rc != 0 ]; then
    # "already exists" is PROOF the remote is there — a failed view was a check that did not work,
    # not an absent repo. Only an unexplained failure is fatal.
    if printf '%s' "$out" | grep -qi 'already exists'; then
      say "create says the name already exists — re-verifying"
      gh repo view "$SLUG" >/dev/null 2>&1 && { say "remote confirmed present: $SLUG"; return 0; }
      die "create says it exists but view still fails — check auth or network"
    fi
    printf '%s\n' "$out" >&2; die "gh repo create $SLUG failed"
  fi
  gh repo view "$SLUG" >/dev/null 2>&1 || die "created $SLUG but view still fails"
  say "remote created and VERIFIED: $SLUG"; }

resolve_repo(){ local d="$ROOT/$LOCAL"
  if [ -d "$d/.git" ]; then
    local o; o="$(cd "$d" && git remote get-url origin 2>/dev/null || true)"
    case "$o" in *"$SLUG"*) :;; *) die "$LOCAL exists but origin is '$o'";; esac
    say "repo reuse: $LOCAL"
  elif [ -e "$d" ]; then die "$LOCAL exists and is not a clone"
  else
    if have gh && gh repo view "$SLUG" >/dev/null 2>&1; then say "cloning $SLUG -> $LOCAL"
      gh repo clone "$SLUG" "$d" -- -q || die "gh repo clone failed"
    else say "initialising $LOCAL"; mkdir -p "$d"
      ( cd "$d" && git init -q -b "$BRANCH" && git remote add origin "$FORGE/$SLUG.git" ); fi; fi
  ( cd "$d" && { git rev-parse --verify -q "$BRANCH" >/dev/null 2>&1 && git checkout -q "$BRANCH"; } \
      || git checkout -q -b "$BRANCH" ) 2>>"$LOG"
  REPO="$d"; inside "$REPO" || die "$LOCAL resolved outside \$PWD"; }

overlay(){ say "laying kitab plumbing + @@SLUG@@ data"
  local d="$REPO" p f
  for p in index.html js readers assets .nojekyll .gitignore; do
    [ -e "$TPL/$p" ] && cp -a "$TPL/$p" "$d/" 2>>"$LOG"; done
  mkdir -p "$d/config" "$d/content" "$d/assets/figures" "$d/metadata" "$d/readers"
  rm -f "$d"/content/*.json
  cp -f "$SRC"/payload/content/*.json "$d/content/"
  cp -f "$SRC"/payload/book.config.json "$d/config/book.config.json"
  for f in readers.config.json features.config.json; do
    [ -f "$TPL/config/$f" ] && cp -f "$TPL/config/$f" "$d/config/$f"; done
  # the template ships Lorem-Ipsum placeholders; they were minted once. assets/figures is DATA.
  rm -f "$d"/assets/figures/*.json "$d"/assets/figures/placeholder-*.svg "$d"/assets/figures/cover.svg
  cp -a "$SRC"/payload/assets/. "$d/assets/" 2>>"$LOG"
  cp -f "$SRC"/metadata/misty.json "$d/metadata/misty.json"
  # the ONE new thing kitab does not ship: a reader module for a cued media block
  cp -f "$SRC"/readers/media.js "$d/readers/media.js" 2>/dev/null || true
  for f in CONTRACT.md CONTEXT.md README.md; do
    [ -f "$SRC/overlays/$f" ] && cp -f "$SRC/overlays/$f" "$d/$f"; done
  python3 - "$d" "$SLUG" <<'PY'
import json, sys, os
d, slug = sys.argv[1], sys.argv[2]
b = os.path.join(d, "config/book.config.json"); k = json.load(open(b))
k["meta"]["repo"] = slug
json.dump(k, open(b, "w"), indent=2, ensure_ascii=False); open(b, "a").write("\n")
# declare the media reader so core.js can render the block
c = os.path.join(d, "config/readers.config.json")
if os.path.exists(c):
    r = json.load(open(c))
    r.setdefault("modules", {})["media"] = "readers/media.js"
    json.dump(r, open(c, "w"), indent=2, ensure_ascii=False); open(c, "a").write("\n")
print("  repo -> %s · media reader declared" % slug)
PY
  [ -f "$d/.gitignore" ] || printf 'logs/\ndoi-package/\n*.tar\n*.tar.gz\n' > "$d/.gitignore"
  touch "$d/.nojekyll"; }

contract(){ say "contract checks"; local bad=0
  [ -f "$REPO/index.html" ] || { warn "index.html missing at ROOT"; bad=1; }
  [ -f "$REPO/js/core.js" ] || warn "js/core.js absent — kitab plumbing did not come across"
  [ -f "$REPO/readers/media.js" ] || warn "readers/media.js absent — the media block will not render"
  local n; n=$(ls -1 "$REPO"/content/*.json 2>/dev/null | wc -l); say "  chapters: $n"
  [ "$n" = "$NCHAP" ] || { warn "expected $NCHAP chapters, found $n"; bad=1; }
  [ -z "$MEDIA" ] || [ -f "$REPO/assets/$MEDIA" ] || { warn "the media file $MEDIA is not in assets/"; bad=1; }
  say "  media:    ${MEDIA:-none} ($(du -h "$REPO/assets/$MEDIA" 2>/dev/null | cut -f1))"
  python3 - "$REPO" "$SLUG" <<'PY' || bad=1
import json, os, sys
d, slug = sys.argv[1], sys.argv[2]; ok = True
def bad(m):
    global ok; ok = False; print("  FAIL " + m)
cfg = json.load(open(os.path.join(d, "config/book.config.json")))
if cfg["meta"]["repo"] != slug: bad("meta.repo != " + slug)
if cfg["meta"]["doi"] is not None: bad("meta.doi must be null before mint")
med = (cfg["meta"].get("media") or {}).get("file")
if med and not os.path.exists(os.path.join(d, med)): bad("declared media missing: " + med)
seen = set()
for c in cfg["structure"]["chapters"]:
    p = os.path.join(d, c["source"])
    if not os.path.exists(p): bad("missing " + c["source"]); continue
    doc = json.load(open(p))
    for b in doc["blocks"]:
        if b["type"] in ("video", "audio"):
            if not os.path.exists(os.path.join(d, b["src"])): bad("media missing: " + b["src"])
            if b.get("end") and b["end"] <= b.get("start", 0): bad("cue ends before it starts in " + c["id"])
            seen.add(b["src"])
if len(seen) > 1: print("  note: %d distinct media files" % len(seen))
for v in ("chatgpt","gemini","claude","openai","anthropic"):
    if v in json.dumps(cfg).lower(): bad("AI vendor named in a text layer: " + v)
print("  config/content/media triangle: " + ("OK" if ok else "FAILED"))
sys.exit(0 if ok else 1)
PY
  [ "$bad" = 0 ] || die "contract failed — nothing staged upstream"; say "contract: PASS"; }

stamp_file(){ local f="$1"; [ -f "$f" ] || return 1
  [ -f "$f.ots" ] && { say "already stamped: $(basename "$f")"; return 0; }
  if [ "${MISTY_HAS_OTS:-unknown}" = "unknown" ]; then MISTY_HAS_OTS=0
    if have misty && misty --help 2>&1 | grep -qw 'ots'; then
      misty ots --help 2>&1 | grep -qw 'stamp' && MISTY_HAS_OTS=1; fi; fi
  if [ "$MISTY_HAS_OTS" = 1 ]; then
    misty ots stamp "$f" >>"$LOG" 2>&1 && { say "stamped via misty ots stamp: $(basename "$f")"; return 0; }
    warn "misty ots stamp failed on $(basename "$f") — nothing fabricated"; return 1; fi
  have ots && ots stamp "$f" >>"$LOG" 2>&1 && { say "stamped via ots: $(basename "$f")"; return 0; }
  warn "no OTS client — NOTHING STAMPED, NOTHING FABRICATED"; return 1; }

seal(){ local d="$REPO" intent="$1"
  mkdir -p "$d/attest/receipts" "$d/attest/history"
  local rc="$d/attest/receipts/$STAMP-seed-@@SLUG@@.json"
  printf '{\n  "protocol": "candor/v1",\n  "utc": "%s",\n  "operation": "seed_@@SLUG@@.sh %s",\n  "repo": "%s",\n  "kind": "%s",\n  "intent": "%s",\n  "agent": "khwab %s"\n}\n' \
    "$STAMP" "$VERSION" "$SLUG" "$KIND" "$intent" "$VERSION" > "$rc"
  stamp_file "$rc"
  if [ -f "$d/MANIFEST.sha256" ]; then
    if [ -f "$d/MANIFEST.sha256.ots" ]; then
      mv "$d/MANIFEST.sha256" "$d/attest/history/$STAMP-MANIFEST.sha256"
      mv "$d/MANIFEST.sha256.ots" "$d/attest/history/$STAMP-MANIFEST.sha256.ots"
    else stamp_file "$d/MANIFEST.sha256" && {
      mv "$d/MANIFEST.sha256" "$d/attest/history/$STAMP-MANIFEST.sha256"
      mv "$d/MANIFEST.sha256.ots" "$d/attest/history/$STAMP-MANIFEST.sha256.ots"; } \
      || warn "outgoing manifest has no proof — NOT archived (C5)"; fi; fi
  ( cd "$d" && git add -A >/dev/null 2>&1
    git ls-files -c -o --exclude-standard | grep -v '^MANIFEST.sha256' | sort | xargs -r sha256sum > MANIFEST.sha256.build 2>/dev/null
    mv MANIFEST.sha256.build MANIFEST.sha256 )
  stamp_file "$d/MANIFEST.sha256"
  ( cd "$d" && sha256sum -c --quiet MANIFEST.sha256 ) \
    && say "manifest VERIFIES ($(wc -l < "$d/MANIFEST.sha256") entries)" || die "manifest does not verify"; }

gate(){ local label="$1" want="$2" ans last="" i=0
  printf '\n[GATE: %s] Type exactly  %s  to proceed (anything else aborts):\n> ' "$label" "$want"
  while [ $i -lt 3 ]; do
    IFS= read -r ans || { ans=""; break; }
    ans="$(printf '%s' "$ans" | tr -d '\r' | sed 's/^ *//;s/ *$//')"
    [ "$ans" = "$want" ] && { printf '%s\n' "$ans" >>"$LOG"; return 0; }
    [ -n "$ans" ] && last="$ans"; i=$((i+1)); done
  say "gate refused (got '${last:-$ans}') — nothing done"; exit 3; }

dirty(){ [ -n "$(cd "$REPO" && git status --porcelain 2>/dev/null)" ]; }

push(){ create_remote_if_needed || die "cannot proceed without a verified remote"
  if ! dirty && [ -n "$(cd "$REPO" && git rev-parse --verify -q HEAD)" ] \
     && [ "$(cd "$REPO" && git rev-parse HEAD)" = "$(git -C "$REPO" ls-remote origin refs/heads/$BRANCH 2>/dev/null | awk '{print $1}')" ]; then
    say "nothing changed and origin/$BRANCH already matches — push skipped (idempotent)"; pages; return 0; fi
  gate "PUSH" "PUSH seed"
  seal "seed @@SLUG@@: $NCHAP $KIND chapters"
  ( cd "$REPO" && git add -A && git -c user.name="${GIT_AUTHOR_NAME:-Abhishek Choudhary}" \
      -c user.email="${GIT_AUTHOR_EMAIL:-noreply@ayeai.xyz}" commit -q -m "attest: seed @@SLUG@@ [$STAMP]" 2>>"$LOG" ) \
    || say "nothing to commit"
  local sha; sha="$(cd "$REPO" && git rev-parse HEAD)"
  git -C "$REPO" push -u origin "$BRANCH" 2>&1 | tee -a "$LOG"
  [ "${PIPESTATUS[0]}" = 0 ] || die "push FAILED — sealed locally, NOT upstream"
  local rs; rs="$(git -C "$REPO" ls-remote origin refs/heads/$BRANCH 2>>"$LOG" | awk '{print $1}')"
  [ "$rs" = "$sha" ] || die "postcondition FAILED: origin=$rs local=$sha"
  say "pushed and VERIFIED: $SLUG @ ${sha:0:7}"
  git -C "$REPO" tag -a "return-to/$STAMP" -m "seed_@@SLUG@@ $VERSION" 2>>"$LOG" || true
  git -C "$REPO" push -q origin "return-to/$STAMP" 2>>"$LOG" || warn "return-to tag not pushed"
  pages; }

pages(){ have gh || { warn "enable Pages: Settings -> Pages -> $BRANCH -> / (root)"; return; }
  gh api -X POST "repos/$SLUG/pages" -f "source[branch]=$BRANCH" -f "source[path]=/" >>"$LOG" 2>&1 \
    && say "Pages enabled: $BRANCH / (root)" || say "Pages already on (or set it in the web UI)"
  say "site: https://$(echo "$SLUG" | cut -d/ -f1).github.io/$(echo "$SLUG" | cut -d/ -f2)/"; }

mint(){ have misty || die "misty absent — pipx install misty-doi. Nothing faked."
  [ -f "$ZENODO_TOKEN_PATH" ] || die "no Zenodo token at $ZENODO_TOKEN_PATH"
  export ZENODO_TOKEN; ZENODO_TOKEN="$(cat "$ZENODO_TOKEN_PATH")"
  [ -n "$ZENODO_TOKEN" ] || die "token file is empty"
  local help; help="$(misty publish --help 2>&1 || true)"; printf '%s\n' "$help" >>"$LOG"
  for fl in '-m' '-f'; do printf '%s' "$help" | grep -q -- "$fl" || die "misty publish lacks $fl"; done
  say "misty interface read: publish advertises -m and -f"
  local pkg="$ROOT/doi-package"; rm -rf "$pkg"; mkdir -p "$pkg"
  ( cd "$REPO" && git ls-files -c --exclude-standard ) | while IFS= read -r f; do
      mkdir -p "$pkg/$(dirname "$f")"; cp -a "$REPO/$f" "$pkg/$f"; done
  local art="$ROOT/@@SLUG@@-$STAMP.tar.gz"; ( cd "$pkg" && tar -czf "$art" . ) || die "packaging failed"
  say "artifact: $(basename "$art")  $(du -h "$art" | cut -f1)"; stamp_file "$art"
  local meta="$REPO/metadata/misty.json"
  misty validate -m "$meta" >>"$LOG" 2>&1 && say "metadata validates" || warn "misty validate reported findings"
  if [ "$OVERRIDE_REHEARSAL" = 0 ]; then
    if misty publish -m "$meta" -f "$art" --sandbox --output "$ROOT/rehearsal.json" >>"$LOG" 2>&1; then say "sandbox rehearsal PASSED"
    else warn "sandbox rehearsal did not complete (sandbox.zenodo.org needs its own token; 403 is the known dead rail)"
      warn "if the RAIL is broken rather than the artifact, rerun with --override-rehearsal"
      die "stopping before the live gate"; fi
  else warn "rehearsal SKIPPED — the live gate is now the only protection"; fi
  say "MINT is the permanent step. The $KIND file is minted with the book."
  gate "MINT" "$MINT_WORD"
  local res="$ROOT/mint-result.$STAMP.json"
  misty publish -m "$meta" -f "$art" --output "$res" 2>&1 | tee -a "$LOG"
  [ "${PIPESTATUS[0]}" = 0 ] || die "misty publish failed — nothing recorded"
  local doi; doi="$(python3 -c "
import json;d=json.load(open('$res'))
for k in ('doi','doi_url','conceptdoi'):
    v=d.get(k) or (d.get('metadata') or {}).get(k)
    if v: print(str(v).replace('https://doi.org/','')); break" 2>/dev/null)"
  [ -n "$doi" ] || die "misty returned no DOI — refusing to guess one"
  say "DOI minted: $doi"
  python3 - "$REPO" "$doi" <<'PY'
import json, sys, os
d, doi = sys.argv[1], sys.argv[2]
b = os.path.join(d, "config/book.config.json"); o = json.load(open(b)); o["meta"]["doi"] = doi
json.dump(o, open(b, "w"), indent=2, ensure_ascii=False); open(b, "a").write("\n")
m = os.path.join(d, "metadata/misty.json"); o = json.load(open(m)); o["doi"] = doi
json.dump(o, open(m, "w"), indent=2, ensure_ascii=False); open(m, "a").write("\n")
print("  DOI recorded back into book.config.json and metadata/misty.json")
PY
  cp -f "$res" "$REPO/MANIFEST.misty"; seal "record DOI $doi and reseal"
  ( cd "$REPO" && git add -A && git -c user.name="${GIT_AUTHOR_NAME:-Abhishek Choudhary}" \
      -c user.email="${GIT_AUTHOR_EMAIL:-noreply@ayeai.xyz}" commit -q -m "attest: record DOI $doi [$STAMP]" 2>>"$LOG" ) || true
  git -C "$REPO" push origin "$BRANCH" 2>&1 | tee -a "$LOG"
  say "https://doi.org/$doi"; }

say "seed_@@SLUG@@.sh $VERSION   target $SLUG   kind $KIND   template $TEMPLATE"
say "working dir: $ROOT  (nothing is written outside it)"
resolve_src; say "payload: $SRC"
resolve_template
create_remote_if_needed || warn "remote not verified yet — --push will create it before sealing"
resolve_repo; overlay; contract
( cd "$REPO" && git add -A >/dev/null 2>&1; git --no-pager diff --cached --stat | tail -4 ) | tee -a "$LOG"
if [ "$DO_PUSH" = 1 ] || [ "$DO_MINT" = 1 ]; then push; else
  say "staged only. Review $LOCAL, then: bash seed_@@SLUG@@.sh --push"; fi
[ "$DO_MINT" = 1 ] && mint
say "done. log: $LOG"
